### ISSUE TITLE
Instrument.calc_projections returns error if only calculating resolution at one point

### ISSUE THREAD

**Issue by pseudocubic** [neutronpy/neutronpy#33]
If `hkle` is only one point then when using `.Instrument.calc_projections` returns the following error

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/neutronpy/resolution.py", line 2455, in plot_projections
    projections = self.projections
AttributeError: 'Instrument' object has no attribute 'projections'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dfobes/Google Drive/Work/LANL/Presentations/resolution_calc/resolution_tests.py", line 18, in <module>
    instr.plot_projections([1,0,0,0])
  File "/usr/local/lib/python3.4/site-packages/neutronpy/resolution.py", line 2457, in plot_projections
    self.calc_projections(hkle, npts)
  File "/usr/local/lib/python3.4/site-packages/neutronpy/resolution.py", line 1917, in calc_projections
    B = A[:3, :3, ind]
IndexError: too many indices for array
```

**Comment by pseudocubic** [comment]
Addressed by 6d864dd2544e0433d9d671789efa8cc8c044d743
