### ISSUE TITLE
Fitter class not working as expected in v0.3.2

### ISSUE THREAD

**Issue by pseudocubic** [neutronpy/neutronpy#35]
Running code that previously worked as expected results in error

```
Traceback (most recent call last):
  File "fig4.old.py", line 256, in <module>
    fitobj = fit_cut(data_bin, p0, fixp, limits, ne)
  File "fig4.old.py", line 138, in fit_cut
    _fitobj.fit(params0=params0)
  File "kmpfit.pyx", line 790, in kmpfit.Fitter.fit (src/kmpfit.c:7543)
RuntimeError: mpfit error, status=-1
```

Last version that is still working is `v0.3.0`, so some change between these two has resulted in the error.

**Comment by pseudocubic** [comment]
After further investigation discovered that this is not a problem with the fitting algorithm, but the detailed balance factor was fixed, so the fitting algorithm was getting negative values for energy gain data (as it should) so the fitting failed with no clear error message.
