### ISSUE TITLE
Setting orientation vectors in Instrument class with list produces error

### ISSUE THREAD

**Issue by pseudocubic** [neutronpy/neutronpy#48]
If `Instrument.sample.u` and/or `Instrument.sample.v` are set to type `list` and not `ndarray` then the following error is thrown when using `Instrument.plot_projections`:

```
Traceback (most recent call last):
  File "resolution_check.py", line 28, in <module>
    instr.plot_projections([1, 1, 0, 0])
  File "/usr/local/lib/python3.5/site-packages/neutronpy/resolution.py", line 2682, in plot_projections
    angles, Q = self.get_angles_and_Q(hkle)
  File "/usr/local/lib/python3.5/site-packages/neutronpy/resolution.py", line 2110, in get_angles_and_Q
    aspv = np.hstack((self.orient1[np.newaxis].T, self.orient2[np.newaxis].T))
TypeError: list indices must be integers or slices, not NoneType
```

`u` and `v` must currently only have `dtype=ndarray` to work properly with the `Instrument.get_angles_and_Q` method. A check needs to be added to resolve.

**Comment by pseudocubic** [comment]
Resolved by b4a7dc00e822451974c0e4f35e3b5fc62b44e8da
