### ISSUE TITLE
crash with npy.gui.launch() and co0.92fe0.08

### ISSUE THREAD

**Issue by bourdarotfromill** [neutronpy/neutronpy#84]
>>> npy.gui.launch()
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/neutronpy/instrument/tools.py", line 213, in GetTau
    return choices[x.lower()]
KeyError: 'co0.92fe0.08'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/neutronpy/gui.py", line 96, in load_instrument
    self.instrument.mono.tau = GetTau(self.mono_select_dropdown.currentText())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/neutronpy/instrument/tools.py", line 215, in GetTau
    raise KeyError('Invalid monochromator crystal type.')
KeyError: 'Invalid monochromator crystal type.'
Abort trap: 6

best regards

F Bourdarot

**Comment by pseudocubic** [comment]
`'co0.92fe0.08'` should be `'co0.92fe0.08(200)'`, and is incorrect in `neutronpy/ui/resolution.ui` on line 338

**Comment by pseudocubic** [comment]
I also realize that I need to fix how errors are captured in the gui so that it doesn't crash but instead just returns the error messages to the user
